### ISSUE TITLE
Can't add float measurements to a process via the API

### ISSUE THREAD

**Issue by stvdwtt** [materials-commons/mcapi#10]
I'm trying to create a process via the API that has a float measurement. I can create the process with no measurements or with an integer measurement. However, if I add a float measurement in the Template Builder on the website, then try to create the process using the API, I get the following error:
![image](https://user-images.githubusercontent.com/10517751/38149614-2db51e76-3429-11e8-99f6-c0335be37fee.png)

I get the same error regardless of whether I try to add a "number" measurement (which looking at the API docs, this is the appropriate function call) or if I don't.

**Comment by Terry-Weymouth** [comment]
I'm going to check into this. I think this fix should be straight forward.

**Comment by Terry-Weymouth** [comment]
To recap, here was the problem that I discovered:

	in the python API code I create a Measurement Class to represent measurements, these classes are subtyped by the object type of the measurement and I had not accounted for “unknown” types - hence the exception - but in a world were measurement object types are changing rapidly, I believe that it is better, in this case, to simply create a generic Measurement object and deal with the consequences downstream. That is the fix that I implemented.

To test this change, and continue working on the lates bate version of the code, you will need to do the following:
1) create (or use) a suitable directory for GitHub downloads, in the illustration I’ll use the name ‘my-gethub’
2) clone the latest fix from the master branch of the materials commons API
3) uninstall your downloaded copy of the materials_commons modules
4) install the material_commons module from the download (GitHub) code (you should see version 0.7.6b0)
5) shake, pour, and enjoy

Specifically:
  mkdir my-gethub
  cd my-gethub
  git clone https://github.com/materials-commons/mcapi.git
  cd mcapi/python
  pip uninstall -y materials_commons
  python setup.py install
  cd <location of sample code>
  python make_measuremsnt.py
